{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "b6cdbdf1_d6f67762",
        "filename": "oem/ibm/requester/dbus_to_file_handler.cpp",
        "patchSetId": 10
      },
      "lineNbr": 130,
      "author": {
        "id": 1000845
      },
      "writtenOn": "2022-09-08T16:59:49Z",
      "side": 1,
      "message": "nit: Can we give context while printing the trace? so that we know when we hit this exception.",
      "range": {
        "startLine": 130,
        "startChar": 22,
        "endLine": 130,
        "endChar": 67
      },
      "revId": "b4efa4ef09c9202249b4a5fdc98ccb0d77f0f6a4",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}